### ISSUE TITLE
Use the images !

### ISSUE THREAD

**Issue by rom1504** [rom1504/web-minecraft-crafter#1]
They are already used a little in the autocomplete list.

Next step is using https://github.com/deathcap/inventory-window to build something like http://minecraft.gamepedia.com/Template:Crafting and display nice recipes.

**Comment by rom1504** [comment]
it might be interesting to reuse https://www.npmjs.com/package/voxel-workbench

**Comment by rom1504** [comment]
@deathcap what do you think I should try using ? inventory-window seems quite usable for displaying recipes, and voxel-workbench is even closer, but it might be a little too specific to use it here. Is it worth trying to use workbench (or some other related module) or should I use inventory-window directly ?

**Comment by rom1504** [comment]
I think I'll just try using inventory-window directly, taking example on https://github.com/voxel/voxel-workbench/blob/master/workbench.coffee#L47

**Comment by rom1504** [comment]
started to work on that in https://github.com/rom1504/web-minecraft-crafter/blob/recipes/main.js

these modular front-end modules are really nice !

**Comment by phase** [comment]
Images in the search box look fine, but when you click on them they get blurry.

![blurry images](http://i.imgur.com/aEPnGUu.png)

**Comment by rom1504** [comment]
Yeah I know, that was just a test, eventually I don't display them that big. (the game textures are small images, they can't really be displayed that big)

**Comment by rom1504** [comment]
Okay it's much better now. Displaying recipes. Opening other issues for further improvements.

**Comment by deathcap** [comment]
@rom1504 looking good, I think your approach of using [inventory-window](https://github.com/deathcap/inventory-window) directly (along with [itempile](https://github.com/deathcap/itempile) and [inventory](https://github.com/deathcap/inventory) modules) is sound. Reusing [voxel-workbench](https://github.com/voxel/voxel-workbench/) could be interesting, but it is more focused on integrating with voxel.js. Maybe [craftingrecipes](https://github.com/deathcap/craftingrecipes) would also be useful though.
